[project]
name = "backup-relayer"
authors = ["Backup Relayer Team"]
description = "A robust backup and relay mechanism for decentralized applications"
telemetry = false
requirements = []
[contracts.backup-relayer]
path = "contracts/backup-relayer.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
